name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vivid-valid/frontend:latest
            ghcr.io/${{ github.repository_owner }}/vivid-valid/frontend:${{ github.sha }}
          build-args: |
            VITE_API_BASE_URL=http://backend:3001/api

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vivid-valid/backend:latest
            ghcr.io/${{ github.repository_owner }}/vivid-valid/backend:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Run Docker Compose tests
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 30
          curl -f http://localhost:8080 || exit 1
          curl -f http://localhost:3012/health || exit 1
          docker compose down
